### PR TITLE
add section8

### PR DESCRIPTION
**Pull request by nayuta723**
## Implementation Summary
I watched section 8 with Working with Microservices in Go (Golang). I installed the gRPC instead of RPC.

## Scope of Impact
/front-end
/broker-service
/logger-service

## Particular points to check
None

## Test
None

## Schedule
8/18
## Reference
[gRPC](https://grpc.io/docs/what-is-grpc/introduction/)

### CODE REVIEW

**Comment by ryuji0123** [comment]
Basically, if there is one scheduled date, it means a deadline for a task. Do you mean reviewers can accept deltas and you can close this issue today?

**Comment by ryuji0123** [comment]
Also, this PR seems to be merged after previous sections are merged. Without any notions, reviewers can review this PR first, which makes them confused since they have difficulty in understanding the code base. You need to write a useful schedule.

**Comment by nayuta723** [comment]
I wrote the schedule, which means the task completion date. I didn't set deadlines for tasks, including code reviews, because I am proceeding with uncertainty about how code reviews should be received.
For Udemy courses that the task does not require code review, can I merge them after the PR is created?

**Comment by ryuji0123** [comment]
> For Udemy courses that the task does not require code review

It depends on your task context. If you want to prioritize progress first, then you can just commit codes and push them into the master or develop branch. But even in that case, you should write tests and make sure that the code base works fine later. BTW, why not decide how to proceed before starting your tasks? When you find uncertainties, you should communicate with someone and make them clear. Of course, this is also the case with others.

**Comment by ryuji0123** [comment]
> But even in that case, you should write tests and make sure that the code base works fine later.

There are at least two reasons for this. First, SWEs must do this. Second, you can find difficulties and understand the code base more through this experience, which can lead you to a better job. As I told you before, students who understand how difficult it is to make code base practical and learn advanced knowledge seems more attractive to hiring people, compared with those who just list products and are unable to talk about deep technical areas.

**Comment by nayuta723** [comment]
Since I want to prioritize progress first, I will commit codes and push them into the master or develop branch.
I will write the test code, etc as long as I finish this lecture (up to section 12).
So, I will merge their PR and push them to the master branch without setting up a branch in the remaining sections.

**Comment by ryuji0123** [comment]
Please write the policy in README and modify or delete existing PRs, following your style.

**Comment by ryuji0123** [comment]
Note that there shouldn't be unnecessary PRs and branches that make others confused.

**Comment by nayuta723** [comment]
Understood, I will proceed accordingly.

**Pull request merged**
